### ISSUE TITLE
Remove unsed waiterbot_controller package

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki-x#13]
in ar_approaching branch.

**Comment by jihoonl** [comment]
its Jorge's implementation of cafe demo. should keep this.

**Comment by bit-pirate** [comment]
It does not even have a package.xml, so I doubt it is used. It looks similar to waiterbot_ctrl_nowireless. I assume you copied it and modified it to your needs. If this is correct, just drop that package. It is still there in the history (and other branches).

**Comment by jihoonl** [comment]
It uses cafe messages which have been used for cafe delivery scenarios.
I have just disabled the package.xml because of library naming conflict.
It is going to be used for cafe delivery. It is not the graveyarded program. It is another controller used for cafe delivery.

**Comment by jihoonl** [comment]
After discussion, decided not remove the controller package since it is controller logic which used for cafe delivery system. Instead, the pakcage has renamed as waiterbot_ctrl_cafe to describe its package purpose better. 

https://github.com/yujinrobot/kobuki-x/commit/cc1e565788201afabfa24f48d3ef42c001e0084d
